server:
  port: 8082

spring:
  application:
    name: account-service

  datasource:
    url: jdbc:mysql://localhost:3306/account
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  jackson:
    serialization:
      INDENT_OUTPUT: true # Indenta o JSON para melhor legibilidade

logging:
  level:
    root: INFO
    org.springframework: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
